name: scrollable_date_picker
description: "Scrollable date picker flutter package."
version: 1.0.2
homepage: https://github.com/PationPrime/Scrollable-Date-Picker

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  super_sliver_list: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
